apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyverno-ca
  labels:
    app: kyverno-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyverno-ca
  template:
    metadata:
      labels:
        app: kyverno-ca
        team: makethecut
    spec:
      containers:
      - name: kyverno-ca
        image: kyverno-ca:v0.0.0
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: kyverno-ca
spec:
  type: NodePort   
  selector:
    app: kyverno-ca
  ports:
  - name: http
    port: 8085
    protocol: TCP
    targetPort: 8085
    nodePort: 30000
